export const enLocalization = {
	sale: 'Sale',
	rent: 'Rent',
	concierge: 'Concierge - service',
	propertyManagement: 'Property management',
	aboutTheCompany: 'About the company',
	aboutPhuket: 'About Phuket',
	news: 'News',
	email: 'E-mail',
	requestACall: 'Request a call',
	resortReal: 'Resort real estate service company in Thailand',
	allServicesInOneCompany: 'All services - ',
	allServicesInOneCompany2: 'in one company',
	weHelpYouBuyProperty: 'We help you buy property in Phuket and Koh Samui, enjoy your life and leisure on the islands and receive rental income',
	learnMore: 'Learn more',
	propertySale: 'Property sale',
	villasAndApartmentsForLife: 'Villas and apartments for life and investment',
	propertyForRent: 'Property for rent',
	premiumAndLuxuryVillas: 'Premium and luxury villas for comfortable vacation',
	anyIssuesAreSolvedForYou: 'Any issues are solved for you - from car rental to entertainment and visa',
	passiveIncomeWithoutWorries: 'Passive income without worries from any corner of the world',
	theBestProjectsForLife: 'The best projects',
	theBestProjectsForLife2: 'for life and investment',
	apartments: 'Apartments',
	villas: 'Villas',
	region: 'Region',
	surin: 'Surin',
	priceFrom: 'Price: from',
	income: 'Income',
	aYear: 'a year',
	more: 'More',
	showTheRest: 'Show the rest',
	offers: 'offers',
	orderAPersonalSelection: 'Order',
	orderAPersonalSelection2: 'a personal selection',
	ourManagerWillCallYou: 'Our manager will call you and compile the property list according to your personal needs and wants',
	yourName: 'Enter your name',
	phoneNumber: 'Enter your phone number',
	byClickingTheRequestACall: 'By clicking the "Request a call" button, I agree to the privacy policy and consent to the processing of personal data',
	requestASelection: 'Request a selection',
	contactUsThroughOurMessengers: 'Contact us through our messengers',
	weAlsoBuildOurselves: 'We also build ourselves',
	weAlsoBuildOurselves2: 'which means you:',
	buyRealEstateOnlyFromTrustedContractors: 'Buy real estate only from trusted contractors',
	getAProfitCalculation: 'Get a profit calculation so you know exactly how much you’ll earn',
	willBeTheFirstToKnow: 'Will be the first to know about real estate market forecasts',
	remainConfidentAndCalm: 'Remain confident and calm: we always fulfill the obligations to you and our investors',
	bangTaoRegion: 'Bang Tao region',
	layanGreenPark: 'Layan Green Park',
	theFirstAparthotelToGainTheEDGE: 'The first aparthotel to gain the EDGE Advanced sustainability certification and to become a part of World Hotels collection. More than 90% of the apartments are sold out at this moment',
	from: 'from',
	learnMoreAbout: 'Learn more',
	fiveSteps: '5 steps',
	fiveSteps2: 'and the property is yours',
	weSelectTheRealEstatePersonally: 'We select the real estate personally for you according to your goals and budget',
	weCalculateProfitability: 'We calculate profitability, familiarize ourselves with facilities and infrastructure',
	weNegotiateWithTheDeveloper: 'We negotiate with the developer to get favorable terms for you and help you close the deal',
	weLegallyAccompanyTheTransaction: 'We legally accompany the transaction: we check the object and help with the documents',
	weTakeCareOfYourPropertyManagement: 'We take care of your property management in Phuket and provide concierge services for you',
	joinThePrivateVillaCarteClub: 'Join the private VillaCarte club',
	youBecomeAClubMember: 'You become a club member after buying or renting a property in Phuket or Koh Samui. Bonuses called Sabai are awarded for each purchasei. They can be spent on renting a villa and a car, visit to a SPA, boat trips and other concierge services.',
	learnMoreSmall: 'Learn more',
	// weAreTrustedBySuccessfulPeople: 'We are trusted by successful people',
	weAreTrustedBySuccessfulPeople: 'Successful people trust us',
	yensBrakerbush: 'Yens Brakerbush',
	cEOofPPGIndustry: 'CEO of PPG Industry',
	review1: 'I have worked with many real estate companies in Thailand, but only VillaCarte has proved their professionalism and responsibility in practice. They found the perfect property for me and helped me through all the necessary procedures to make my transaction safe and profitable. I am very grateful to VillaCarte and would recommend them to anyone looking for property in Thailand',
	okishimaJunichi: 'Okishima Junichi',
	cEOYOKOHAMARUS: 'CEO YOKOHAMA RUS',
	review2: 'Being a client of VillaCarte was a real discovery for me - I did not expect that the service and quality of work could be so high. They helped me choose and buy a property in Thailand, and also carried out all the necessary checks and agreement conditions. I recommend VillaCarte to anyone who is looking for a reliable partner to buy property in Thailand',
	weHaveBeenTakingCare: 'We have been taking care of your vacation and income for more than 10 years',
	inVillaCarteEveryDayWeWork: 'In VillaCarte, every day we work to fulfill your wishes',
	sharingExclusiveContentFromTheIsland: 'Sharing exclusive content from the island',
	watchExpertReviews: 'Watch expert reviews',
	learnAllAboutRealEstateInThailand: 'Learn all about real estate in Thailand',
	montenegro: 'Montenegro',
	phuket: 'Phuket',
	privacyPolicy: 'Privacy Policy',
	VillaCarteAllRights: 'VillaCarte © 2012 - 2023 — All rights and materials reserved',
	websiteDevelopment: 'website development —',
	orderAnIndividualSelection: 'Order an individual selection of real estate',
	byClickingTheSendRequest: 'By clicking the "Send request" button, I consent to the processing of my personal data',
};

export const ruLocalization = {
	sale: 'Продажа',
	rent: 'Аренда',
	concierge: 'Консьерж - сервис',
	propertyManagement: 'Управление недвижимостью',
	aboutTheCompany: 'О компании',
	aboutPhuket: 'О Пхукете',
	news: 'Новости',
	email: 'Почта',
	requestACall: 'Заказать звонок',
	resortReal: 'Сервисная компания по продаже и аренде курортной недвижимости в Таиланде',
	allServicesInOneCompany: 'Все услуги —  ',
	allServicesInOneCompany2: 'в одной компании',
	weHelpYouBuyProperty: 'Помогаем купить недвижимость на Пхукете и Самуи, наслаждаться жизнью и отдыхом на островах и получать доход от аренды',
	learnMore: 'Узнать больше',
	propertySale: 'Продажа недвижимости',
	villasAndApartmentsForLife: 'Виллы и апартаменты для жизни и инвестиций',
	propertyForRent: 'Аренда недвижимости',
	premiumAndLuxuryVillas: 'Виллы премиум- и люкс-класса для комфортного отдыха',
	anyIssuesAreSolvedForYou: 'Решение любых вопросов — от аренды транспорта до развлечений и получения визы',
	passiveIncomeWithoutWorries: 'Пассивный доход из любой точки мира без забот',
	theBestProjectsForLife: 'Лучшие проекты',
	theBestProjectsForLife2: 'для жизни и инвестиций',
	apartments: 'Апартаменты',
	villas: 'Виллы',
	region: 'Район',
	surin: 'Сурин',
	priceFrom: 'Цена: от',
	income: 'Доход',
	aYear: 'в год',
	more: 'Подробнее',
	showTheRest: 'Показать еще',
	offers: 'предложений',
	orderAPersonalSelection: 'Закажите ',
	orderAPersonalSelection2: 'персональную подборку',
	ourManagerWillCallYou: 'Вам позвонит менеджер и подберёт недвижимость под ваши индивидуальные запросы',
	yourName: 'Введите ваше имя',
	phoneNumber: 'Введите ваш номер телефона',
	byClickingTheRequestACall: 'Нажимая кнопку «Заказать подборку», я соглашаюсь с политикой конфиденциальности и даю согласие на обработку персональных данных',
	requestASelection: 'Заказать подборку',
	contactUsThroughOurMessengers: 'Наши месенджеры для связи',
	weAlsoBuildOurselves: 'Строим сами –',
	weAlsoBuildOurselves2: 'а значит вы:',
	buyRealEstateOnlyFromTrustedContractors: 'Покупаете недвижимость только у проверенных подрядчиков',
	getAProfitCalculation: 'Получаете расчёт доходности, чтобы точно знать, сколько заработаете',
	willBeTheFirstToKnow: 'Узнаёте первыми о прогнозах рынка недвижимости',
	remainConfidentAndCalm: 'Остаётесь уверены и спокойны: мы выполняем обязательства перед вами и инвесторами',
	bangTaoRegion: 'Район Банг Тао',
	layanGreenPark: 'Layan Green Park',
	theFirstAparthotelToGainTheEDGE: 'Первый апарт-отель, который получил сертификацию экологичности EDGE Advanced и стал частью коллекции World Hotels. Сейчас в нём продано больше 90% апартаментов',
	from: 'от',
	learnMoreAbout: 'Подробнее об объекте',
	fiveSteps: '5 шагов –',
	fiveSteps2: 'и недвижимость ваша',
	weSelectTheRealEstatePersonally: 'Персонально подбираем недвижимость под ваши цели и бюджет',
	weCalculateProfitability: 'Рассчитываем доходность, знакомим с объектами и инфраструктурой',
	weNegotiateWithTheDeveloper: 'Договариваемся с застройщиком о выгодных для вас условиях и помогаем заключить сделку',
	weLegallyAccompanyTheTransaction: 'Юридически сопровождаем сделку: проверяем объект и помогаем с документами',
	weTakeCareOfYourPropertyManagement: 'Берём на себя управление недвижимостью на Пхукете и предоставляем услуги консьерж-сервиса',
	joinThePrivateVillaCarteClub: 'Присоединяйтесь к закрытому клубу VillaCarte',
	youBecomeAClubMember: 'Вы становитесь членом клуба после покупки или аренды недвижимости на Пхукете или Самуи. За каждую покупку начисляются бонусы — Сабаи. Их можно потратить на аренду виллы и авто, посещение SPA, морские прогулки и другие услуги консьерж-сервиса.',
	learnMoreSmall: 'Подробнее',
	weAreTrustedBySuccessfulPeople: 'Нам доверяют успешные люди',
	yensBrakerbush: 'Йенс Бракебуш',
	cEOofPPGIndustry: 'Генеральный директор PPG Industry',
	review1: 'Я сотрудничал с многими компаниями по приобретению недвижимости в Таиланде, но только VillaCarte доказали свой профессионализм и ответственность на практике. Они нашли для меня идеальный объект недвижимости и помогли провести все необходимые процедуры, чтобы моя сделка была безопасной и выгодной. Я очень благодарен VillaCarte и рекомендую их всем, кто ищет недвижимость в Таиланде',
	okishimaJunichi: 'Окишима Жуничи',
	cEOYOKOHAMARUS: 'Генеральный директор ЙОКОХАМА РУС',
	review2: 'Сотрудничество с VillaCarte стало для меня настоящим открытием — я не ожидал, что сервис и качество работы могут быть настолько высокими. Они помогли мне выбрать и купить недвижимость в Таиланде, а также провели все необходимые проверки и согласования условий. Я рекомендую VillaCarte всем, кто ищет надёжного партнёра для приобретения недвижимости в Таиланде',
	weHaveBeenTakingCare: 'Больше 10 лет заботимся о вашем отдыхе и доходе',
	inVillaCarteEveryDayWeWork: 'Каждый день мы работаем над тем, чтобы исполнять ваши желания в VillaCarte',
	sharingExclusiveContentFromTheIsland: 'Делимся эксклюзивным контентом с острова',
	watchExpertReviews: 'Смотреть экспертные обзоры',
	learnAllAboutRealEstateInThailand: 'Узнать все о недвижимости в Таиланде',
	montenegro: 'Черногория',
	phuket: 'Пхукет',
	privacyPolicy: 'Политика конфиденциальности',
	VillaCarteAllRights: 'VillaCarte © 2012 - 2023 — Все права и материалы защищены',
	websiteDevelopment: 'создание сайтов —',
	orderAnIndividualSelection: 'Закажите индивидуальную подборку недвижимости',
	byClickingTheSendRequest: 'Нажимая кнопку “Отправить запрос” я даю согласие на обработку моих персональных данных',
};
